import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn } from "next-auth/react";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<button
				onClick={() => {
					signIn("github", {
						callbackUrl: "http://localhost:3000/dashboard",
					});
				}}
			>
				SignIn
			</button>
		</div>
	);
}
